CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE education
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institution VARCHAR(255)                            NOT NULL,
    degree      VARCHAR(255)                            NOT NULL,
    start_date  date                                    NOT NULL,
    end_date    date                                    NOT NULL,
    CONSTRAINT pk_education PRIMARY KEY (id)
);

CREATE TABLE experience
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company    VARCHAR(255)                            NOT NULL,
    position   VARCHAR(255)                            NOT NULL,
    start_date date                                    NOT NULL,
    end_date   date                                    NOT NULL,
    CONSTRAINT pk_experience PRIMARY KEY (id)
);

CREATE TABLE experience_mission
(
    experience_id BIGINT NOT NULL,
    mission       VARCHAR(255)
);

CREATE TABLE portfolio
(
    id               BIGINT       NOT NULL,
    name             VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    current_position VARCHAR(255) NOT NULL,
    photo            VARCHAR(255) NOT NULL,
    CONSTRAINT pk_portfolio PRIMARY KEY (id)
);

CREATE TABLE project
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    link        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE project_screenshot
(
    project_id BIGINT NOT NULL,
    screenshot VARCHAR(255)
);

CREATE TABLE project_technology
(
    project_id BIGINT NOT NULL,
    technology VARCHAR(255)
);

CREATE TABLE skill
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_skill PRIMARY KEY (id)
);

ALTER TABLE skill
    ADD CONSTRAINT FK_SKILL_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE experience_mission
    ADD CONSTRAINT fk_experience_mission_on_experience_entity FOREIGN KEY (experience_id) REFERENCES experience (id);

ALTER TABLE project_screenshot
    ADD CONSTRAINT fk_project_screenshot_on_project_entity FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_technology
    ADD CONSTRAINT fk_project_technology_on_project_entity FOREIGN KEY (project_id) REFERENCES project (id);