quarkus.http.port=8080
quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:portfolio}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:portfolio}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/portfolio}
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.min-size=5

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.bind-parameters=false
